language: ruby

rvm:
  - 2.3.8
  - 2.4.4
  - 2.5.3
  - 2.6.1
  - ruby-head
  - jruby-head
  - truffleruby-head

script: "bundle exec rake --trace"

matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  recipients:
    - nahi@ruby-lang.org
